[build-system]
requires = ["psutil>=5.9.0", "setuptools>=45", "setuptools_scm[toml]>=6.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "artisatomic"
authors = [
    {name = "ARTIS Collaboration", email = "luke.shingles@gmail.com"},
]
description="Tools to create an atomic database for use with ARTIS."
readme = "README.md"
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dynamic = ["version", "dependencies", "entry-points"]
requires-python = ">=3.10"

[project.scripts]
makeartisatomicfiles = "artisatomic:main"
makerecombratefile = "artisatomic.makerecombratefile:main"

[tool.black]
line-length = 120

[tool.mypy]
python_version = '3.11'
exclude = "(build)|(tests)"
packages = "artisatomic"
ignore_missing_imports = true
warn_unused_configs = true

[tool.pylint]
max-line-length = 120
errors-only = true

[tool.pylint.typecheck]
ignored-modules = ["astropy", "extinction"]

[tool.ruff]
select = [
    #"ALL",
    "A", "B", "C", "D", "E", "F", "G", "N", "Q", "W", "ARG", "BLE", "DJ", "DTZ", "EM", "ERA", "EXE",
    "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PYI", "RET", "RSE", "RUF",
    "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"
]
ignore = [
    "ARG001", # ignored because variables in df.eval() are not detected
    "B005",
    "B007", # variable not used in loop body (but sometimes it is with eval)
    "BLE001",
    "C9",
    "COM812",
    "D100", "D101", "D102", "D103", "D104", "D107", "D203", "D205", "D213", "D401", "D417",
    "E501", "E741",
    "EM101","EM102",
    "ERA001",
    "F841", # ignored because variables in df.eval() are not detected
    "ISC001",
    "N802", "N803", "N806", "N999","N816",
    "PD901",
    "PGH001",
    "PLR0911", "PLR0912", "PLR0913", "PLR0915", "PLR2004",
    "PLW2901",
    "PT011",
    "PYI024",
    "RET504",
    "SIM115",
    "SLF001",
    "TRY003",
    "TRY301",
    "UP032",
]
fixable = ["ALL"]
unfixable = [
    "COM812",  # missing-trailing-comma
    "ERA001",  # commented-out-code (will just delete it!)
    "F841",  # unused-variable
    "RUF100", # unused-noqa
    "SIM222", # expr-or-true
    "SIM223", # expr-and-false
    "TCH005", # empty-type-checking-block
    "F401",
]
line-length = 120
target-version = "py310"

[tool.ruff.isort]
force-single-line = true
order-by-type = false

[tool.setuptools_scm]
write_to = "_version.py"
local_scheme = "no-local-version"
