[build-system]
requires = ["psutil>=5.9.0", "setuptools>=45", "setuptools_scm[toml]>=6.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "artisatomic"
authors = [
    {name = "ARTIS Collaboration", email = "luke.shingles@gmail.com"},
]
description="Tools to create an atomic database for use with ARTIS."
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
]
dynamic = ["version", "dependencies", "entry-points"]
requires-python = ">=3.9"

[tool.black]
line-length = 120
preview = true

[tool.mypy]
python_version = '3.11'
exclude = "(build)|(tests)"
packages = "artisatomic"
ignore_missing_imports = true
warn_unused_configs = true

[tool.pylint]
max-line-length = 120
errors-only = true

[tool.pylint.typecheck]
ignored-modules = ["astropy", "extinction"]

[tool.ruff]
select = [
    #"ALL",
    "A", "B", "C", "D", "E", "F", "G", "N", "Q", "W", "ARG", "BLE", "DJ", "DTZ", "EM", "ERA", "EXE",
    "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PYI", "RET", "RSE", "RUF",
    "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"
]
ignore = [
    "ARG001", # ignored because variables in df.eval() are not detected
    "B005",
    "B007", # variable not used in loop body (but sometimes it is with eval)
    "BLE001",
    "C9",
    "COM812",
    "D100", "D101", "D102", "D103", "D104", "D107", "D203", "D205", "D213", "D401", "D417",
    "E501", "E741",
    "EM101","EM102",
    "ERA001",
    "F841", # ignored because variables in df.eval() are not detected
    "N802", "N803", "N806", "N999",
    "PD901",
    "PGH001",
    "PLR0911", "PLR0912", "PLR0913", "PLR0915", "PLR2004",
    "PLW2901",
    "PT011",
    "RET504",
    "SIM115",
    "SLF001",
    "TRY003",
    "TRY301",
    "UP032",
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = [
    "A", "B", "C", "D", "E", "G", "N", "Q", "W", "ARG", "BLE", "DJ", "DTZ", "EM", "ERA", "EXE",
    "FBT", "ICN", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PLR", "PT", "PTH", "PYI", "RET", "RSE",
    "RUF", "SIM", "SLF", "TCH", "TID", "UP", "YTT"
]
unfixable = [
    "ERA001",  # commented out code (will just delete it!)
    "F841",
    "F401",
    "PD002"
]

# larger than black's limit. Let black handle this
line-length = 200

target-version = "py39"

[tool.setuptools_scm]
write_to = "_version.py"
local_scheme = "no-local-version"
