name: Build and test

on: [push]

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout Code
      uses: actions/checkout@v2.3.4

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache pip
      uses: actions/cache@v2.1.4
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
         ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Install artisatomic
      run: |
        python -m pip install -e .

    - name: Lint with flake8
      working-directory: artisatomic/
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Cache CMFGEN atomic data
      uses: actions/cache@v2.1.4
      id: cache-cmfgendata
      with:
          path: "atomic-data-hillier/atomic_data_15nov16.tar.xz"
          key: "atomic-data-hillier/atomic_data_15nov16.tar.xz"

    - name: Download CMFGEN atomic data
      if: steps.cache-cmfgendata.outputs.cache-hit != 'true'
      working-directory: atomic-data-hillier/
      run: |
          curl -O https://psweb.mp.qub.ac.uk/artis/artisatomic/atomic-data-hillier/atomic_data_15nov16.tar.xz
          md5sum -c atomic_data_15nov16.tar.xz.md5

    - name: Extract CMFGEN atomic data
      working-directory: atomic-data-hillier/
      run: |
          tar -xzf atomic_data_15nov16.tar.xz
          rsync -a atomic_diff/ atomic/

    - name: Test with pytest
      run: |
        pytest

    - name: Generate artis atomic data files
      run: |
        makeartisatomicfiles -output_folder test_output

    - name: Checksum output files
      run: |
        md5sum test_output/*.txt
        md5sum -c <(echo b8f6bc739894a563cb55ee83a9a81f8c test_output/adata.txt)
        md5sum -c <(echo 2e3bd7a2e27ee823afa9977e1b4dc2a5 test_output/compositiondata.txt)
        md5sum -c <(echo cb0b9a2e5952986b9d99fff3cf9855d6 test_output/phixsdata_v2.txt)
        md5sum -c <(echo cd240462da8b7e55b6ead0d0bd3adb40 test_output/transitiondata.txt)

    - name: tar and zip output files
      run: |
        tar -cvzf artis_files.tar.gz test_output/*

    - name: Upload output files
      uses: actions/upload-artifact@v2
      with:
        name: artis_files.tar.gz
        path: artis_files.tar.gz
