name: Build and test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy
        python -m pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Cache cmfgenatomicdata
      uses: actions/cache@v2.1.4
      id: cache-cmfgendata
      with:
          path: "atomic-data-hillier"
          key: atomic_data_15nov16.tar.gz
    - name: Download and extract CMFGEN atomic data
      if: steps.cache-cmfgendata.outputs.cache-hit != 'true'
      run: |
          cd atomic-data-hillier/
          curl -O http://kookaburra.phyast.pitt.edu/hillier/cmfgen_files/atomic_data_15nov16.tar.gz
          tar -xvzf atomic_data_15nov16.tar.gz
          rsync -av atomic_diff/ atomic/
          cd ..
    - name: Generate artis atomic data files
      run: |
        find atomic-data-hillier -type d
        makeartisatomicfiles -output_folder test_output

    - name: Upload output files
      uses: actions/upload-artifact@v2
      with:
        name: artis_files-output
        path: test_output